env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode11.7
      script:
        - set -o pipefail
        - xcodebuild -scheme "Euclid" -sdk macosx clean build test
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t 2abe208f-c7d5-4c0d-aaf7-fa6994f1a78e
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test
